// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEVOXRX_UqhFs5TYLtJlOdiKMOCDpP5mU',
    appId: '1:627579204732:web:b74ace89d46bc3e29945f9',
    messagingSenderId: '627579204732',
    projectId: 'twitter-flutter-hvp230822',
    authDomain: 'twitter-flutter-hvp230822.firebaseapp.com',
    storageBucket: 'twitter-flutter-hvp230822.appspot.com',
    measurementId: 'G-3VZ7BS264J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbVYXSdEylamcmA1ppIO8CPNIszzUiGNY',
    appId: '1:627579204732:android:e75671b85571179c9945f9',
    messagingSenderId: '627579204732',
    projectId: 'twitter-flutter-hvp230822',
    storageBucket: 'twitter-flutter-hvp230822.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkhalNFM_0G88Ev-GeHrXp7khOasquLNU',
    appId: '1:627579204732:ios:84816f251e1f5f809945f9',
    messagingSenderId: '627579204732',
    projectId: 'twitter-flutter-hvp230822',
    storageBucket: 'twitter-flutter-hvp230822.appspot.com',
    iosClientId: '627579204732-bg7q58g6bfiugdiii94pqa4a01hrrb0i.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitterFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkhalNFM_0G88Ev-GeHrXp7khOasquLNU',
    appId: '1:627579204732:ios:84816f251e1f5f809945f9',
    messagingSenderId: '627579204732',
    projectId: 'twitter-flutter-hvp230822',
    storageBucket: 'twitter-flutter-hvp230822.appspot.com',
    iosClientId: '627579204732-bg7q58g6bfiugdiii94pqa4a01hrrb0i.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitterFlutter',
  );
}
